# Generated by Django 6.0.4 on 2026-04-24 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('is_python_unlocked', models.BooleanField(default=True)),
                ('is_java_unlocked', models.BooleanField(default=False)),
                ('is_cpp_unlocked', models.BooleanField(default=False)),
                ('exp', models.IntegerField(default=0)),
                ('unlocked_level', models.IntegerField(default=1)),
                ('completed_levels', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
